"""add member fields

Revision ID: 4f93b89cd8d5
Revises: a806d5ecae88
Create Date: 2026-03-11 06:00:37.351557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f93b89cd8d5'
down_revision: Union[str, None] = 'a806d5ecae88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('members', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('significant_other', sa.String(), nullable=True))
    op.add_column('members', sa.Column('address', sa.String(), nullable=True))
    op.add_column('members', sa.Column('city', sa.String(), nullable=True))
    op.add_column('members', sa.Column('state', sa.String(), nullable=True))
    op.add_column('members', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('members', sa.Column('home_phone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('work_phone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('mobile_phone', sa.String(), nullable=True))
    op.add_column('members', sa.Column('membership_type', sa.String(), nullable=True))
    op.add_column('members', sa.Column('skill_level', sa.String(), nullable=True))
    op.add_column('members', sa.Column('years_turning', sa.String(), nullable=True))
    op.add_column('members', sa.Column('volunteer_interest', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('volunteer_area', sa.String(), nullable=True))
    op.add_column('members', sa.Column('how_heard', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'how_heard')
    op.drop_column('members', 'volunteer_area')
    op.drop_column('members', 'volunteer_interest')
    op.drop_column('members', 'years_turning')
    op.drop_column('members', 'skill_level')
    op.drop_column('members', 'membership_type')
    op.drop_column('members', 'mobile_phone')
    op.drop_column('members', 'work_phone')
    op.drop_column('members', 'home_phone')
    op.drop_column('members', 'zip_code')
    op.drop_column('members', 'state')
    op.drop_column('members', 'city')
    op.drop_column('members', 'address')
    op.drop_column('members', 'significant_other')
    op.drop_column('members', 'birthday')
    op.drop_column('members', 'nickname')
    # ### end Alembic commands ###
