"""add updated_at to members

Revision ID: 85e32c152a76
Revises: 3e1dd292f70e
Create Date: 2026-03-12 16:10:43.425350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e32c152a76'
down_revision: Union[str, None] = '3e1dd292f70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'updated_at')
    # ### end Alembic commands ###
