"""add status and dues fields

Revision ID: 962625e74a90
Revises: 4f93b89cd8d5
Create Date: 2026-03-11 06:15:47.546769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962625e74a90'
down_revision: Union[str, None] = '4f93b89cd8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('status', sa.String(), nullable=True))
    op.add_column('members', sa.Column('dues_paid', sa.Boolean(), nullable=True))
    op.add_column('members', sa.Column('dues_paid_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'dues_paid_date')
    op.drop_column('members', 'dues_paid')
    op.drop_column('members', 'status')
    # ### end Alembic commands ###
